version: '3.8'
name: news-site

services:
  database:
    container_name: news-site-database
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '5306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - news-site

  app:
    container_name: news-site-app
    restart: unless-stopped
    build:
      context: php
    volumes:
      - ./app:/var/www/app
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=NewsSite"
    depends_on:
      - database
    networks:
      - news-site

  nginx:
    container_name: news-site-nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - news-site

networks:
  news-site:
    driver: bridge
